version: '3'

services:

  weather:
    build: ./weather-information-api
    ports:
      - "8080:8080"
      - "6379:6379"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  javatest:
    build: ./weather-information-data-api-test-java
    container_name: javatest
    depends_on:
      weather:
        condition: service_healthy
    links: 
        - weather
