version: '3'

services:

  weather-info:
    build: ./weather-information-api
    ports:
      - "8080:8080"
      - "6379:6379"

  java-test:
    build: ./weather-information-data-api-test-java
    container_name: java-test
    depends_on:
      - weather-info

  pytest:
    build: ./weather-information-data-api-test
    container_name: pytest
    depends_on:
      - weather-info